### ISSUE TITLE
Niet sorteren & ctr+s bug

### ISSUE THREAD

**Issue by lnieuwenhuis** [Dr-Doofus/code-levels#2]
De verschillende talen worden niet gesorteerd op levels, dat zou wel fijn zijn. En er is een bug, wanneer je ctr+s ingedrukt houdt (blijft saven) gaat de meter nog steeds omhoog voor de taal van het document en het totale XP.

**Comment by Dr-Doofus** [comment]
De "bug" waar je Ctrl+S ingedrukt houdt was al bekend sinds het begin, maar dit zal niet opgelost worden. Dit heeft te maken met het gebruik van de `workspace.onDidChangeTextDocument` event. Er is een andere manier om dat te doen maar dat houdt de letter wat al getypt is vast totdat de code klaar is met uitvoeren.

Ik heb ervoor gekozen om niet talen te sorteren op levels zodat je via `views.pinsForUser` en `views.pinsForWorkspace` het zelf kan sorteren.

**Comment by Dr-Doofus** [comment]
Blijkbaar is deel van deze issue gefixt in versie 1.7.5. Het sorteren blijft zo zodat het mogelijk is om per workspace de levels zelf te sorteren.
