### ISSUE TITLE
VSCode crash due to inefficient code messing up and breaking everything

### ISSUE THREAD

**Issue by joploljojo3** [Dr-Doofus/code-levels#7]
When username is made too long (around 100MB of text) it crashes the entirety of vscode due to inefficient code. this is a very obvious and dumb bug, that shouldn't have been missed in testing
![image](https://github.com/Dr-Doofus/code-levels/assets/122799644/7c45ff4d-0b6a-492f-bb13-444bc64403b3)

**Comment by joploljojo3** [comment]
# hippity hoppity this has priority

**Comment by Dr-Doofus** [comment]
My mistake for VS Code no longer automatically ignoring invalid settings. The package itself specifies a 32 character limit on usernames but actually does nothing to enforce it. I'll have to look into this and will be fixed next update.

**Comment by Dr-Doofus** [comment]
This problem has been resolved as not only the extension checks its type but also hard-trims the string if it is too long.
It will be shipped in the next version.
